services:
  cab:
    container_name: cab
    restart: always
    network_mode: host
    build:
      context: .
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8001:8001"

  redis:
    image: redis:6.2-alpine
    container_name: cab-redis
    restart: always
    network_mode: host
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 1s
      timeout: 3s
      retries: 10

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: cab-chrome
    restart: always
    hostname: chrome
    privileged: true
    shm_size: 2g
    ports:
      - "5901:5900"
      - "4445:4444"

volumes:
  cache:
    driver: local
